kmjennison/dfp-prebid-setup

- requirements.txt
> Fix typos in requirements.txt

- dfp/get_orders.py
> Use `print` as compatible with Python 3

- tasks/add_new_prebid_partner.py
- tests/test_add_new_prebid_partner.py
> Replace `raw_input` with `input`

- requirements.txt
- tasks/add_new_prebid_partner.py
> Support logging colors on Windows

- README.md
- dfp/create_creatives.py
- dfp/create_orders.py
- settings.py
- tasks/add_new_prebid_partner.py
- tests/test_add_new_prebid_partner.py
- tests/test_dfp_create_creatives.py
- tests/test_dfp_create_orders.py
> Support for adding multiple creatives to line items

- dfp/associate_line_items_and_creatives.py
- dfp/create_creatives.py
- dfp/create_custom_targeting.py
- dfp/create_orders.py
- dfp/get_advertisers.py
- dfp/get_custom_targeting.py
- dfp/get_orders.py
- dfp/get_placements.py
- dfp/get_users.py
- tasks/add_new_prebid_partner.py
- tests/test_add_new_prebid_partner.py
- tests/test_dfp_get_orders.py
Use unicode strings when we print or log values.
Fixes #15
> Fix unicode display errors

- dfp/create_line_items.py
- settings.py
- tasks/add_new_prebid_partner.py
- tests/test_add_new_prebid_partner.py
- tests/test_dfp_create_line_items.py
> Allow custom currency code

- dfp/associate_line_items_and_creatives.py
- tests/test_dfp_associate_line_items_and_creatives.py
> Remove unneeded 1x1 default ad size

- dfp/get_custom_targeting.py
> Add loop so that cache may get more than 500 key value results

- tests/test_dfp_get_custom_targeting.py
> Fix test for DFP getting custom targeting

- README.md
- dfp/create_line_items.py
- dfp/get_ad_units.py
- settings.py
- tasks/add_new_prebid_partner.py
- tests/test_add_new_prebid_partner.py
- tests/test_dfp_create_line_items.py
- tests/test_dfp_get_ad_units.py
First of all, thanks for making this nice utility! 
I tried to implement support to target ad units instead of placements, and it worked great on our account. Thus I decided to wrap up the changes and send this pull request.
Please have a look first and if everything looks good, I'll try to add some basic test, update READMEs etc.
This close #17
> Add support to target ad units

- .travis.yml
- README.md
- dfp/associate_line_items_and_creatives.py
- dfp/create_creatives.py
- dfp/create_custom_targeting.py
- dfp/create_line_items.py
- dfp/create_orders.py
- dfp/get_advertisers.py
- dfp/get_custom_targeting.py
- dfp/get_orders.py
- dfp/get_placements.py
- dfp/get_users.py
- requirements.txt
- tests_integration/helpers/archive_order_by_name.py
- tests_integration/helpers/get_advertiser_by_name.py
- tests_integration/helpers/get_custom_targeting_by_key_name.py
- tests_integration/helpers/get_line_items_for_order.py
- tests_integration/helpers/get_order_by_name.py
- tests_integration/helpers/get_placement_by_name.py
- tests_integration/integration_test_new_prebid_partner.py
> Update googleads version

- tasks/price_utils.py
> Remove max CPM, which does not work well with some currencies

- tests_integration/integration_test_new_prebid_partner.py
Lingering version in a test.  Best to do a find and replace on the repo and change all the old api references each time.
> Fix ref to old api version in test file.

- dfp/get_ad_units.py
I think https://github.com/kmjennison/dfp-prebid-setup/pull/81 miss one googleads version.
> Update missing googleads version

- dfp/associate_line_items_and_creatives.py
Tiny amendment to fix the notice of items generated.
> Fix line item total in log message.

- dfp/associate_line_items_and_creatives.py
- dfp/create_creatives.py
- dfp/create_custom_targeting.py
- dfp/create_line_items.py
- dfp/create_orders.py
- dfp/get_ad_units.py
- dfp/get_advertisers.py
- dfp/get_custom_targeting.py
- dfp/get_orders.py
- dfp/get_placements.py
- dfp/get_users.py
- requirements.txt
- tests_integration/helpers/archive_order_by_name.py
- tests_integration/helpers/get_advertiser_by_name.py
- tests_integration/helpers/get_custom_targeting_by_key_name.py
- tests_integration/helpers/get_line_items_for_order.py
- tests_integration/helpers/get_order_by_name.py
- tests_integration/helpers/get_placement_by_name.py
- tests_integration/integration_test_new_prebid_partner.py
> Upgrade Ad Manager API version

- dfp/creative_snippet.html
Update the DFP Creative snipped based on the new one:
https://github.com/prebid/prebid-universal-creative#usage
> Update Prebid Universal Creative snippet to include `hbPb` in tag data

- dfp/associate_line_items_and_creatives.py
- dfp/create_creatives.py
- dfp/create_custom_targeting.py
- dfp/create_line_items.py
- dfp/create_orders.py
- dfp/get_ad_units.py
- dfp/get_advertisers.py
- dfp/get_custom_targeting.py
- dfp/get_orders.py
- dfp/get_placements.py
- dfp/get_users.py
- requirements.txt
- tests_integration/helpers/archive_order_by_name.py
- tests_integration/helpers/get_advertiser_by_name.py
- tests_integration/helpers/get_custom_targeting_by_key_name.py
- tests_integration/helpers/get_line_items_for_order.py
- tests_integration/helpers/get_order_by_name.py
- tests_integration/helpers/get_placement_by_name.py
- tests_integration/integration_test_new_prebid_partner.py
> Update Ad Manager API version

- dfp/associate_line_items_and_creatives.py
- dfp/create_creatives.py
- dfp/create_custom_targeting.py
- dfp/create_line_items.py
- dfp/create_orders.py
- dfp/get_ad_units.py
- dfp/get_advertisers.py
- dfp/get_custom_targeting.py
- dfp/get_orders.py
- dfp/get_placements.py
- dfp/get_users.py
API version v202305 is disabled.
> Update API version
